name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

  push:
    tags:
      - 'v*'  # 当推送新标签时触发

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: 'Install dependencies'
        run: python -m pip install pandas openpyxl

      - name: Run res/auto_generate_item_file.py
        run: python res/auto_generate_item_file.py

      - name: Create a zip of the directory for EN-US
        run: zip -r BoxItemEditor_EN-US.zip reframework -x "reframework/fonts/*" "*ZH-Hans*" "reframework/data/*ZH-Hans.json"

      - name: Create a zip of the directory for ZH-Hans
        run: zip -r BoxItemEditor_ZH-Hans.zip reframework -x "*EN-US*" "reframework/data/*EN-US.json"

      - name: Generate checksums
        run: |
          sha256sum BoxItemEditor_EN-US.zip > BoxItemEditor_EN-US.zip.sha256
          sha256sum BoxItemEditor_ZH-Hans.zip > BoxItemEditor_ZH-Hans.zip.sha256

      - name: Check if release exists and delete it
        run: |
          if gh release view ${{ github.event.inputs.tag || github.ref_name }}; then
            gh release delete ${{ github.event.inputs.tag || github.ref_name }} --yes
          fi

      - name: Prepare release notes
        id: generate_notes
        run: |
          echo "### 版本下载 / Release Downloads" > release_notes.md
          echo "> `reframework`目录中包含物品ID列表 / The `reframework` directory contains item ID list." >> release_notes.md
          echo "- **[BoxItemEditor_EN-US.zip](https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.tag || github.ref_name }}/BoxItemEditor_EN-US.zip)** （英文版 / English Version）" >> release_notes.md
          echo "- **[BoxItemEditor_ZH-Hans.zip](https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.tag || github.ref_name }}/BoxItemEditor_ZH-Hans.zip)** （简体中文版 / Simplified Chinese Version）" >> release_notes.md
          echo "" >> release_notes.md
          echo "### 文件校验 / Checksums" >> release_notes.md
          echo "- \`BoxItemEditor_EN-US.zip\` SHA-256: $(cut -d ' ' -f1 BoxItemEditor_EN-US.zip.sha256)" >> release_notes.md
          echo "- \`BoxItemEditor_ZH-Hans.zip\` SHA-256: $(cut -d ' ' -f1 BoxItemEditor_ZH-Hans.zip.sha256)" >> release_notes.md
          echo "### 打包时间 / Build Time" >> release_notes.md
          echo "- $(date)" >> release_notes.md

      - name: Create GitHub Release
        id: create_release
        run: |
          gh release create ${{ github.event.inputs.tag || github.ref_name }} *.zip --title "${{ github.event.inputs.tag || github.ref_name }} Release" --notes-file release_notes.md

      - name: Commit changes
        run: |
          git config --local user.email "dzxrly2@gmail.com"
          git config --local user.name "dzxrly2"
          git add .
          git commit -m ":truck: 更新物品ID列表"
          git push -f origin HEAD:main
